### ISSUE TITLE
hey check it out

### ISSUE THREAD

**Issue by ghost** [aarnhub/sms-bomber#1]
`Progress: 1/1 9433936727 Missing "from" parameter
== Error. Text messages not sent ==
Progress: 2/1 9433936727 Missing "from" parameter
== Error. Text messages not sent ==
Progress: 3/1 9433936727 Missing "from" parameter
== Error. Text messages not sent ==`

**Comment by ghost** [comment]
One more thing there was no number i got in that site you provided

**Comment by aarnhub** [comment]
Hi! Please check if you are using valid Proovl.com number and token.
